// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEif7M2992zsSwPdZ5Zx-BozW-ki5mAys',
    appId: '1:141394141818:web:08dc11092492ee196851c3',
    messagingSenderId: '141394141818',
    projectId: 'simpleconnect-34554',
    authDomain: 'simpleconnect-34554.firebaseapp.com',
    storageBucket: 'simpleconnect-34554.firebasestorage.app',
    measurementId: 'G-V4ZYZR2R9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChEFfHrrmPPmLNjtst8RbUmR0aJs3GGM0',
    appId: '1:141394141818:android:e15c1d2e27b9f5686851c3',
    messagingSenderId: '141394141818',
    projectId: 'simpleconnect-34554',
    storageBucket: 'simpleconnect-34554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDwKCMYVdfcW3MSKK-mCgOT8PPbAW9qs8',
    appId: '1:141394141818:ios:7461360557d96aeb6851c3',
    messagingSenderId: '141394141818',
    projectId: 'simpleconnect-34554',
    storageBucket: 'simpleconnect-34554.firebasestorage.app',
    iosBundleId: 'com.siva.echat',
  );
}
